--- 
title: "Latest News"
author: "cbc.ca"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: rstudio/bookdown-demo
description: "Latest news from cbc.ca."
---

# From US
## Rudy Giuliani subpoenaed as Trump slams impeachment probe
[Read from source](https://www.cbc.ca/news/world/giuliani-subpoenae-schiff-treason-1.5302521)

The U.S. House of Representatives' impeachment probe into President Donald Trump intensified on Monday, as Trump raged about the inquiry and news reports suggested he had used additional diplomatic channels to go after his adversaries.

Three House committees said a subpoena for documents had been sent to Trump's lawyer Rudy Giuliani. The former New York mayor had said on television he asked the government of Ukraine to "target" former vice-president Joe Biden, who is seeking the Democratic nomination to run against Trump in the 2020 election.

Giuliani said in a tweet the subpoena raised legal issues including attorney-client privilege. "It will be given appropriate consideration," he added.

The subpoena notes Giuliani recently said he has "evidence — in the form of text messages, phone records, and other communications" indicating he was not acting alone and that other Trump administration officials "may have been involved." 


# From Canada
## 'Beefier barley' researcher says her work does not promote positives of climate change 
[Read from source](https://www.cbc.ca/news/canada/edmonton/beefier-barley-researcher-1.5303627)

A university researcher whose work was used in controversial billboards around Edmonton and Calgary says her work was not intended to portray any positive effects of climate change.

"It was not quite pleasant to see how your research results could be misinterpreted" — in the "beefier barley" ads — "but that's not something I can take control of," said Monireh Faramarzi, an associate professor of environmental sciences at the University of Alberta

Faramarzi published research in 2017, exploring how climate change and increased carbon dioxide levels could potentially affect barley production in Alberta. A potential result could be higher barley yields despite less natural rainfall for crops, she found. 

The research went relatively unnoticed in the broader public realm until recently, when billboards referencing it were used in the university's Truth Matters campaign.
